name: "Stremio IPTV addon"
version: "1.1.7"
slug: "stremio_iptv_addon"
description: "Add-on Stremio per Live TV tramite M3U, EPG e routing su EasyProxy."
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: application
boot: auto
host_network: true
init: false

options:
  port: 3000
  m3u_url: "https://raw.githubusercontent.com/leanhhu061206/LIVETV/refs/heads/main/zappruaznao.m3u"
  epg_url: ""
  refresh_interval_minutes: 60
  easyproxy_url: "http://192.168.1.xxx:8080"
  easyproxy_password: ""

schema:
  port: "port"
  m3u_url: "str"
  epg_url: "str?"
  refresh_interval_minutes: "int"
  easyproxy_url: "str"
  easyproxy_password: "password?"
