name: "EasyProxy Light"
version: "2.1.0"
slug: "easyproxy"
description: "Server Proxy Universale HLS (Versione Light). Porta fissa 7860."
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
ports:
  7860/tcp: 7860
webui: "http://[HOST]:7860"
options:
  global_proxy: ""
  transport_routes: ""
  mpd_mode: "legacy"
  password: ""
  log_level: "WARNING"
schema:
  global_proxy: "str?"
  transport_routes: "str?"
  mpd_mode: "list(legacy|ffmpeg)"
  password: "password?"
  log_level: "list(DEBUG|INFO|WARNING|ERROR|CRITICAL)"
map:
  - "config:rw"
init: false
