name: "EasyProxy Light"
version: "2.2.0"
slug: "easyproxy"
description: "Server Proxy Universale HLS (Versione Light)."
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
host_network: true

options:
  port: 7860
  global_proxy: ""
  transport_routes: ""
  password: ""
  log_level: "INFO"

schema:
  port: "port"
  global_proxy: "str?"
  transport_routes: "str?"
  password: "password?"
  log_level: "list(DEBUG|INFO|WARNING|ERROR|CRITICAL)"

map:
  - "config:rw"
init: false
