name: StreamViX
version: "1.4.1"
slug: streamvix
description: A Stremio addon that extracts streaming sources from various Italian sites
url: https://github.com/qwertyuiop8899/StreamViX
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
map:
  - config:rw
ports:
  7860/tcp: 7860
ports_description:
  7860/tcp: StreamViX Web Interface
options:
  MFP_URL: ""
  MFP_PSW: ""
  TMDB_API_KEY: ""
  ANIMEUNITY_ENABLED: false
  ANIMESATURN_ENABLED: true
  ENABLE_MPD_STREAMS: false
  ENABLE_LIVE_TV: true
  FAST_DYNAMIC: false
  DYNAMIC_EXTRACTOR_CONC: 10
  DYNAMIC_PURGE_HOUR: 8
  DYNAMIC_DISABLE_RUNTIME_FILTER: true
  DYNAMIC_KEEP_YESTERDAY: false
schema:
  MFP_URL: str?
  MFP_PSW: password?
  TMDB_API_KEY: str?
  ANIMEUNITY_ENABLED: bool
  ANIMESATURN_ENABLED: bool
  ENABLE_MPD_STREAMS: bool
  ENABLE_LIVE_TV: bool
  FAST_DYNAMIC: bool
  DYNAMIC_EXTRACTOR_CONC: int(1,50)
  DYNAMIC_PURGE_HOUR: int(0,23)
  DYNAMIC_DISABLE_RUNTIME_FILTER: bool
  DYNAMIC_KEEP_YESTERDAY: bool
# Build from source instead of using pre-built image
# image: "ghcr.io/yourusername/ha-streamvix/{arch}"
  TMDB_API_KEY: str?
  ANIMEUNITY_ENABLED: bool
  ANIMESATURN_ENABLED: bool
  ENABLE_MPD_STREAMS: bool
  ENABLE_LIVE_TV: bool
  FAST_DYNAMIC: bool
  DYNAMIC_EXTRACTOR_CONC: int(1,50)
  DYNAMIC_PURGE_HOUR: int(0,23)
  DYNAMIC_DISABLE_RUNTIME_FILTER: bool
  DYNAMIC_KEEP_YESTERDAY: bool
image: "ghcr.io/yourusername/ha-streamvix/{arch}"
