name: StreamViX
version: "1.4.1"
slug: streamvix
description: >-
  A Stremio addon that extracts streaming sources from various Italian sites
  including VixSrc, AnimeUnity, AnimeSaturn, and live TV channels.
url: https://github.com/qwertyuiop8899/StreamViX
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
init: false
hassio_api: true
hassio_role: default
host_network: false
stage: stable
map:
  - config:rw
ports:
  7860/tcp: 7860
ports_description:
  7860/tcp: StreamViX Web Interface
webui: "http://[HOST]:[PORT:7860]"
options:
  mfp_url: ""
  mfp_password: ""
  tmdb_api_key: ""
  animeunity_enabled: false
  animesaturn_enabled: true
  enable_mpd_streams: false
  enable_live_tv: true
  fast_dynamic: false
  dynamic_extractor_conc: 10
  dynamic_purge_hour: 8
  dynamic_disable_runtime_filter: true
  dynamic_keep_yesterday: false
  log_level: info
schema:
  mfp_url: url?
  mfp_password: password?
  tmdb_api_key: str?
  animeunity_enabled: bool
  animesaturn_enabled: bool
  enable_mpd_streams: bool
  enable_live_tv: bool
  fast_dynamic: bool
  dynamic_extractor_conc: int(1,50)
  dynamic_purge_hour: int(0,23)
  dynamic_disable_runtime_filter: bool
  dynamic_keep_yesterday: bool
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
