name: "StreamViX"
version: "1.0.0"
slug: "ha-streamvix"    <--- ECCO LA CORREZIONE IMPORTANTE
description: "Un addon per Stremio che estrae sorgenti streaming per film, serie TV, anime, TV live ed Eventi Sportivi."
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
host_network: true
options:
  port: 7860
  mfp_url: ""
  mfp_password: ""
  tmdb_api_key: ""
  addon_base_url: ""
  animeunity_enabled: true
  animesaturn_enabled: true
  enable_live_tv: true
  streamed_enable: true
  rbtv_enable: true
  spso_enable: true
  pd_enable: false
  tvtap_enable: false
  fast_dynamic: false
  dynamic_extractor_conc: 10
schema:
  port: "port"
  mfp_url: "str?"
  mfp_password: "password?"
  tmdb_api_key: "str?"
  addon_base_url: "str?"
  animeunity_enabled: "bool"
  animesaturn_enabled: "bool"
  enable_live_tv: "bool"
  streamed_enable: "bool"
  rbtv_enable: "bool"
  spso_enable: "bool"
  pd_enable: "bool"
  tvtap_enable: "bool"
  fast_dynamic: "bool"
  dynamic_extractor_conc: "int"
map:
  - "config:rw"
init: false
