build_from:
  aarch64: "ghcr.io/hassio-addons/base-nodejs:0.2.3"
  amd64: "ghcr.io/hassio-addons/base-nodejs:0.2.3"
  armhf: "ghcr.io/hassio-addons/base-nodejs:0.2.3"
  armv7: "ghcr.io/hassio-addons/base-nodejs:0.2.3"
  i386: "ghcr.io/hassio-addons/base-nodejs:0.2.3"
labels:
  org.opencontainers.image.title: "WordPress"
  org.opencontainers.image.description: "WordPress CMS per Home Assistant"
  org.opencontainers.image.source: "https://github.com/username/repository-name"
  org.opencontainers.image.licenses: "MIT"
args:
  WORDPRESS_VERSION: "6.4.2"
