name: WordPress
description: Wordpress for Home Assistant
version: "1.0.0"
slug: wordpress
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: https://github.com/dartanidi/ha-addons
boot: auto
ports:
  80/tcp: 8188
ports_description:
  80/tcp: Porta HTTP per WordPress
map:
  - config
  - ssl
options:
  db_name: wordpress
  db_user: wordpress
  db_password: password
  db_host: core-mariadb
  db_prefix: wp_
  db_charset: utf8mb4
  db_collate: ""
schema:
  db_name: str
  db_user: str
  db_password: str
  db_host: str
  db_prefix: str
  db_charset: str
  db_collate: str
